IF(EXISTS(SELECT NAME FROM sysobjects WHERE NAME = 'RPY511' AND xtype = 'P'))
	DROP PROCEDURE RPY511
GO

CREATE PROC RPY511 (
		@JSNYER		AS NVARCHAR(6),		--귀속년도
		@CLTCOD     AS Nvarchar(8),     --자사코드
		@MSTDPT     AS Nvarchar(8),     --부서
	    @MSTCOD 	AS NVARCHAR(8) 	   	--사원번호		
	) 

AS
    /*==========================================================================================
        프로시저명      : RPY511
        프로시저설명    : 기부금 명세서
        만든이          : 송정호
        작업일자        : 2011-02-24
        작업지시자      : 
        작업지시일자    : 
        작업목적        : 
        작업내용        : 
    ===========================================================================================*/
    -- DROP PROC RPY511
    -- Exec RPY511 '2010','%', '%', '%'

    SET NOCOUNT ON

-- <1.임시테이블 생성 >ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

	CREATE TABLE #RPY511 (
		DocEntry	Int,
		U_CLTNAM	NVARCHAR(50),
		U_BusNum	NVARCHAR(12),
		U_MSTNAM	NVARCHAR(50),
		U_PERNBR	NVARCHAR(14),
		U_ADDRES	NVARCHAR(100),
		U_PERCAL	NVARCHAR(13),
		U_POSADD	NVARCHAR(100),
		U_POSCAL	NVARCHAR(13),
		-- 기부 합계
		U_GIBTOT	NUMERIC(19,6),
		U_LAWTOT	NUMERIC(19,6),
		U_POCTOT	NUMERIC(19,6),
		U_SPETOT	NUMERIC(19,6),
		U_GONTOT	NUMERIC(19,6),
		U_JIJTOT	NUMERIC(19,6),
		U_JNGTOT	NUMERIC(19,6),
		U_USJTOT	NUMERIC(19,6),
		U_GITTOT	NUMERIC(19,6),
		-- 본인 기부금
		U_BONTOT	NUMERIC(19,6),
		U_LAWBON	NUMERIC(19,6),
		U_POCBON	NUMERIC(19,6),
		U_SPEBON	NUMERIC(19,6),
		U_GONBON	NUMERIC(19,6),
		U_JIJBON	NUMERIC(19,6),
		U_JNGBON	NUMERIC(19,6),
		U_USJBON	NUMERIC(19,6),
		U_GITBON	NUMERIC(19,6),
		-- 배우자 기부금
		U_BAETOT	NUMERIC(19,6),
		U_LAWBAE	NUMERIC(19,6),
		U_SPEBAE	NUMERIC(19,6),
		U_GONBAE	NUMERIC(19,6),
		U_JIJBAE	NUMERIC(19,6),
		U_JNGBAE	NUMERIC(19,6),
		U_GITBAE	NUMERIC(19,6),
		-- 직계비속 기부금
		U_JIGTOT	NUMERIC(19,6),
		U_LAWJIG	NUMERIC(19,6),
		U_SPEJIG	NUMERIC(19,6),
		U_GONJIG	NUMERIC(19,6),
		U_JIJJIG	NUMERIC(19,6),
		U_JNGJIG	NUMERIC(19,6),
		U_GITJIG	NUMERIC(19,6),
		-- 직계존속 기부금
		U_JONTOT	NUMERIC(19,6),
		U_LAWJON	NUMERIC(19,6),
		U_SPEJON	NUMERIC(19,6),
		U_GONJON	NUMERIC(19,6),
		U_JIJJON	NUMERIC(19,6),
		U_JNGJON	NUMERIC(19,6),
		U_GITJON	NUMERIC(19,6),
		-- 형제자매 기부금
		U_BNSTOT	NUMERIC(19,6),
		U_LAWBNS	NUMERIC(19,6),
		U_SPEBNS	NUMERIC(19,6),
		U_GONBNS	NUMERIC(19,6),
		U_JIJBNS	NUMERIC(19,6),
		U_JNGBNS	NUMERIC(19,6),
		U_GITBNS	NUMERIC(19,6),
		-- 그 외 기부금
		U_ETCTOT	NUMERIC(19,6),
		U_LAWETC	NUMERIC(19,6),
		U_SPEETC	NUMERIC(19,6),
		U_GONETC	NUMERIC(19,6),
		U_JIJETC	NUMERIC(19,6),
		U_JNGETC	NUMERIC(19,6),
		U_GITETC	NUMERIC(19,6)
	)

-- <2.정산자료 조회 >ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

	INSERT	INTO [#RPY511]
	SELECT	DocEntry    =   T2.DocEntry,
			U_CLTNAM	=	MAX(T1.Name),
			U_BusNum	=	MAX(T1.U_BusNum),
			U_MSTNAM	=	MAX(T0.U_FullName),
			U_PERNBR	=	ISNULL(MAX(T0.U_govID),''),
			U_ADDRES	=	ISNULL(MAX(T0.U_ADDRESS),''),
			U_PERCAL	=	ISNULL(MAX(T0.U_HomeTel),''),
			U_POSADD	=	MAX(T1.U_PosAdd),
			U_POSCAL	=	MAX(T1.U_TelNum),
			
			U_GIBTOT	=	SUM(CASE WHEN LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_POCTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '20' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPETOT    =   SUM(CASE WHEN T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_USJTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '42' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITTOT    =   SUM(CASE WHEN T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			
			U_BONTOT    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_POCBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '20' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPEBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_USJBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '42' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITBON    =   SUM(CASE WHEN T3.U_GWANGE = '1' AND T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),

			U_BAETOT    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWBAE    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPEBAE    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONBAE    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJBAE    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGBAE    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITBAE    =   SUM(CASE WHEN T3.U_GWANGE = '2' AND T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),

			U_JIGTOT    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWJIG    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPEJIG    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONJIG    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJJIG    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGJIG    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITJIG    =   SUM(CASE WHEN T3.U_GWANGE = '3' AND T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			
			U_JONTOT	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWJON	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPEJON	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONJON	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJJON	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGJON	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITJON	=   SUM(CASE WHEN T3.U_GWANGE = '4' AND T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			
			U_BNSTOT	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWBNS	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPEBNS	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONBNS	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJBNS	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGBNS	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITBNS	=   SUM(CASE WHEN T3.U_GWANGE = '5' AND T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			
			U_ETCTOT	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_LAWETC	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND T3.U_GBUCOD = '10' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_SPEETC	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND T3.U_GBUCOD = '30' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GONETC	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND T3.U_GBUCOD = '31' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JIJETC	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND T3.U_GBUCOD = '40' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_JNGETC	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND T3.U_GBUCOD = '41' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END),
			U_GITETC	=   SUM(CASE WHEN T3.U_GWANGE = '6' AND T3.U_GBUCOD = '50' AND LEFT(T3.U_GBUYMM,4) = T2.U_JSNYER THEN T3.U_GBUAMT ELSE 0 END)

	FROM	[@ZPY505H] T2 
			INNER JOIN [@ZPY505L] T3 ON T2.DocEntry = T3.DocEntry  
			INNER JOIN [@PH_PY001A] T0 ON T2.U_MSTCOD = T0.Code
			INNER JOIN [@PH_PY005A] T1 ON T0.U_CLTCOD = T1.U_CLTCode
			
	WHERE	T2.U_JSNYER = @JSNYER 
	AND		T2.U_CLTCOD LIKE @CLTCOD 
	AND		T0.U_TeamCode LIKE @MSTDPT 
	AND		T2.U_MSTCOD LIKE @MSTCOD  
	GROUP	BY T2.DocEntry, T2.U_JSNYER, T2.U_CLTCOD, T2.U_MSTCOD

-- <3.정산자료 조회 >ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ    
    
    SELECT * FROM [#RPY511]

	SET NOCOUNT OFF