IF(EXISTS(SELECT NAME FROM sysobjects WHERE NAME = 'RPY401_2' AND xtype = 'P'))
	DROP PROCEDURE RPY401_2
GO

CREATE  PROC RPY401_2
	(
		@STRDAT 	AS Nvarchar(10), 	--시작일자
		@ENDDAT 	AS Nvarchar(10), 	--종료일자
		@JOBGBN		AS Nvarchar(1), 	--작업구분(1연말정산,2중도정산,3전체)
		@Branch		AS Nvarchar(8), 	--지점
		@MSTDPT		AS Nvarchar(8), 	--부서
	    @MSTCOD 	AS Nvarchar(8), 	--사원번호
	    @STRJIG 	AS Nvarchar(10), 	--지급시작일자
		@ENDJIG 	AS Nvarchar(10) 	--지급종료일자
	)
	WITH Encryption  

 AS
    /*==========================================================================================
        프로시저명      : RPY401_2
        프로시저설명    : 퇴직소득원천징수영수증 - 제2서식
        만든이          : 최동권
        작업일자        : 2009-02-04
        작업지시자      : 함미경
        작업지시일자    : 2009-02-04
        작업목적        : 퇴직소득 원천징수영수증을 출력
        작업내용        : 
    ===========================================================================================*/
	--DROP PROC RPY401_2
	

SET NOCOUNT ON
--<1.임시테이블생성>ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ    

	CREATE TABLE #RPY401 (
	        DocNum	   	Int,
			U_MSTCOD	NVARCHAR(8),
			U_MSTNAM	NVARCHAR(50),
			U_EmpID		NVARCHAR(8),
			U_INTGBN	NVARCHAR(1),
			U_DWEGBN	NVARCHAR(1),
			U_FRGTAX	NVARCHAR(1),
			U_FRGCOD	NVARCHAR(6),
			U_BUBCHK	NVARCHAR(1),
			U_BUSNUM	NVARCHAR(12),
			U_CLTNAM	NVARCHAR(50),
			U_COMPRT	NVARCHAR(30),
			U_COMNBR	NVARCHAR(20),
			U_POSADD	NVARCHAR(200),	
			U_PERNBR	NVARCHAR(20),
			U_ADDRES	NVARCHAR(200),	
			U_STRINT	NVARCHAR(10),
			U_ENDINT	NVARCHAR(10),
			U_RETRES	NvarChar(8), 
			U_SPCGBN	NvarChar(1),
			U_TJKPAY	NUMERIC(19,6),
			U_ADDPAY	NUMERIC(19,6),
			U_YILPA1	NUMERIC(19,6),
			U_YILPA2	NUMERIC(19,6),
			U_RETPAY	NUMERIC(19,6),
			U_J01NAM	NVARCHAR(40),
			U_J01NBR	NVARCHAR(12),
			U_JS1SPC	NVARCHAR(1),
			U_JRET01	NUMERIC(19,6),
			U_JADD01	NUMERIC(19,6),
			U_JYIL03	NUMERIC(19,6),
			U_JYIL04	NUMERIC(19,6),
			U_JTOT01	NUMERIC(19,6),
			U_JTOT02	NUMERIC(19,6),
			U_BGWASE	NUMERIC(19,6),
			U_BTAP01	NUMERIC(19,6),
			U_MYNACC	NVARCHAR(20),
			U_MYNTOT	NUMERIC(19,6),
			U_MYNWON	NUMERIC(19,6),
			U_MYNBUL	NUMERIC(19,6),
			U_MYNGON	NUMERIC(19,6),
			U_MYNCOM	NVARCHAR(50),
			U_MYNCNO	NVARCHAR(50),
			U_IPGMIL	NVARCHAR(10),
			U_MANGIL	NVARCHAR(10),
			U_YILPAY	NUMERIC(19,6),
			U_JYNACC	NVARCHAR(20),
			U_JYNTOT	NUMERIC(19,6),
			U_JYNWON	NUMERIC(19,6),
			U_JYNBUL	NUMERIC(19,6),
			U_JYNGON	NUMERIC(19,6),
			U_JYIL01	NUMERIC(19,6),
			U_SH1JIG	NUMERIC(19,6),
			U_SH3JIG	NUMERIC(19,6),
			U_SH1IYO	NUMERIC(19,6),
			U_SH3IYO	NUMERIC(19,6),
			U_SH1GSU	NUMERIC(19,6),
			U_SH3GSU	NUMERIC(19,6),
			U_SH1TIL	NUMERIC(19,6),
			U_SH1SUR	NUMERIC(19,6),
			U_SH1GON	NUMERIC(19,6),
			U_SH1GWA	NUMERIC(19,6),
			U_SH1YAG	NUMERIC(19,6),
			U_SH1YAS	NUMERIC(19,6),
			U_SH2JIG	NUMERIC(19,6),
			U_SH4JIG	NUMERIC(19,6),
			U_SH2IYO	NUMERIC(19,6),
			U_SH4IYO	NUMERIC(19,6),
			U_SH2GSU	NUMERIC(19,6),
			U_SH4GSU	NUMERIC(19,6),
			U_SH2TIL	NUMERIC(19,6),
			U_SH2SUR	NUMERIC(19,6),
			U_SH2GON	NUMERIC(19,6),
			U_SH2GWA	NUMERIC(19,6),
			U_SH2YAG	NUMERIC(19,6),
			U_SH2YAS	NUMERIC(19,6),
			U_GNMMON	INT,
			U_EXPMON	INT,
			U_GNMYER	INT,
--			U_ST2RET	NVARCHAR(10),	
--			U_EN2RET	NVARCHAR(10),	
			U_GN2MON	INT,		
			U_EX2MON	INT,		
			U_GN2YER	INT,		
			U_JINDAT	NVARCHAR(10),
			U_JOTDAT	NVARCHAR(10),
			U_JONMON	INT,		
			U_JEXMON	INT,		
			U_JMMMON	INT,		
			U_JI2DAT	NVARCHAR(10),
			U_JO2DAT	NVARCHAR(10),
			U_JO2MON	INT,
			U_JE2MON	INT,
			U_JM2MON	INT,
			U_JS1RET	NUMERIC(19,6),
			U_JS1GON	NUMERIC(19,6),
			U_JS1STD	NUMERIC(19,6),
			U_JS1YSD	NUMERIC(19,6),
			U_JS1YST	NUMERIC(19,6),
			U_JS1SAN	NUMERIC(19,6),
			U_JS1STX	NUMERIC(19,6),
			U_JS1TAX	NUMERIC(19,6),
			U_JS1GAB	NUMERIC(19,6),
			U_JS2RET	NUMERIC(19,6),
			U_JS2GON	NUMERIC(19,6),
			U_JS2STD	NUMERIC(19,6),
			U_JS2YSD	NUMERIC(19,6),
			U_JS2YST	NUMERIC(19,6),
			U_JS2SAN	NUMERIC(19,6),
			U_JS2STX	NUMERIC(19,6),
			U_JS2TAX	NUMERIC(19,6),
			U_JS2GAB	NUMERIC(19,6),
			U_JSNRET	NUMERIC(19,6),
			U_RETGON	NUMERIC(19,6),
			U_TAXSTD	NUMERIC(19,6),
			U_YTXSTD	NUMERIC(19,6),
			U_YSANTX	NUMERIC(19,6),
			U_SANTAX	NUMERIC(19,6),
			U_SPCGON	Numeric(19,6),
			U_TAXGON	NUMERIC(19,6),
			U_GULGAB	NUMERIC(19,6),
			U_GULJUM	NUMERIC(19,6),
			U_JONGAB	NUMERIC(19,6),
			U_JONJUM	NUMERIC(19,6),
			U_CHAGAB	NUMERIC(19,6),
			U_CHAJUM	NUMERIC(19,6),
			U_TAXNAM	NVARCHAR(20),
			U_STRRET	NVARCHAR(10),
			U_ENDRET	NVARCHAR(10),
			U_INPDAT	NVARCHAR(10),
			U_OUTDAT	NVARCHAR(10),
            U_FIFIMG    image NULL)
	        
-- <2.정산자료 조회 >ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ    
	INSERT	INTO [#RPY401]
	SELECT	DocNum	   	=	T0.DocEntry,
			U_MSTCOD	=	T0.U_MSTCOD,
			U_MSTNAM	=	T0.U_MSTNAM,
			U_EmpID		=	T0.U_EmpID,
			U_INTGBN	=	T1.U_INTGBN,
			U_DWEGBN	=	T1.U_DWEGBN,
			U_FRGTAX	=	T1.U_FRGTAX,
			U_FRGCOD	=	T1.U_brthCntr,
			U_BUBCHK	=	'',
			U_BUSNUM	=	ISNULL(T2.U_BusNum, ''),
			U_CLTNAM	=	ISNULL(T2.U_CLTName, ''),
			U_COMPRT	=	ISNULL(T2.U_ComPrt, ''),
			U_COMNBR	=	ISNULL(T2.U_PerNum, ''),
			U_POSADD	=	ISNULL(T2.U_PosAdd, ''),	
			U_PERNBR	=	ISNULL(T1.U_GovID, ''),
			U_ADDRES	=	ISNULL(T1.U_Address, ''),	
			U_STRINT	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_STRINT,120),''),
			U_ENDINT	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_ENDINT,120),''),
			ISNULL(T0.U_RETRES,''), ISNULL(T0.U_SPCGBN,'N'), 
			U_TJKPAY	=	T0.U_TJKPAY, 
			U_ADDPAY	=	T0.U_SUDAMT,
			U_YILPA1	=	T0.U_YILPA1,
			U_YILPA2	=	T0.U_YILPA2,
			U_RETPAY	=	T0.U_RETPAY,
			U_J01NAM	=	T0.U_J01NAM,
			U_J01NBR	=	T0.U_J01NBR,
			U_JS1SPC	=	ISNULL(T0.U_JS1SPC,'N'),
			U_JRET01	=	T0.U_JRET01,
			U_JADD01	=	T0.U_JADD01,
			U_JYIL03	=	T0.U_JYIL03,
			U_JYIL04	=	T0.U_JYIL04,
			U_JTOT01	=	T0.U_JTOT01,
			U_JTOT02	=	T0.U_JTOT02, 
			U_BGWASE	=	T0.U_BTXPAY,
			U_BTAP01	=	T0.U_BTXP01,
			U_MYNACC	=	T0.U_MYNACC,
			U_MYNTOT	=	T0.U_MYNTOT,
			U_MYNWON	=	T0.U_MYNWON,
			U_MYNBUL	=	T0.U_MYNBUL,
			U_MYNGON	=	T0.U_MYNGON,
			U_MYNCOM	=	T0.U_MYNCOM,
			U_MYNCNO	=	T0.U_MYNCNO,
			U_IPGMIL	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_IPGMIL,120),''),
			U_MANGIL	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_MANGIL,120),''),
			U_YILPAY	=	T0.U_YILPAY,
			U_JYNACC	=	T0.U_JYNACC,
			U_JYNTOT	=	T0.U_JYNTOT,
			U_JYNWON	=	T0.U_JYNWON,
			U_JYNBUL	=	T0.U_JYNBUL,
			U_JYNGON	=	T0.U_JYNGON,
			U_JYIL01	=	T0.U_JYIL01,
			U_SH1JIG	=	T0.U_SH1JIG,	-- 환산-지급예상액
			U_SH3JIG	=	T0.U_SH3JIG,	-- 환산-지급예상액
			U_SH1IYO	=	T0.U_SH1IYO,	-- 환산-과세이연금액-주(현)
			U_SH3IYO	=	T0.U_SH3IYO,	-- 환산-과세이연금액-종(전)
			U_SH1GSU	=	T0.U_SH1GSU,	-- 환산-기수령한퇴직급여액-주(현)
			U_SH3GSU	=	T0.U_SH3GSU,	-- 환산-기수령한퇴직급여액-종(전)
			U_SH1TIL	=	T0.U_SH1TIL,	-- 환산-총일시금
			U_SH1SUR	=	T0.U_SH1SUR,	-- 환산-수령가능액
			U_SH1GON	=	T0.U_SH1GON,	-- 환산-소득공제 
			U_SH1GWA	=	T0.U_SH1GWA,	-- 환산-과세표준
			U_SH1YAG	=	T0.U_SH1YAG,	-- 환산-연평균과세표준
			U_SH1YAS	=	T0.U_SH1YAS,	-- 환산-연평균산출세
			U_SH2JIG	=	T0.U_SH2JIG,
			U_SH4JIG	=	T0.U_SH4JIG,
			U_SH2IYO	=	T0.U_SH2IYO,
			U_SH4IYO	=	T0.U_SH4IYO,
			U_SH2GSU	=	T0.U_SH2GSU,
			U_SH4GSU	=	T0.U_SH4GSU,
			U_SH2TIL	=	T0.U_SH2TIL,
			U_SH2SUR	=	T0.U_SH2SUR,
			U_SH2GON	=	T0.U_SH2GON,
			U_SH2GWA	=	T0.U_SH2GWA,
			U_SH2YAG	=	T0.U_SH2YAG,
			U_SH2YAS	=	T0.U_SH2YAS,
			U_GNMMON	=	T0.U_GNMMON,
			U_EXPMON	=	T0.U_EXPMON,
			U_GNMYER	=	T0.U_GNMYER,
--			U_ST2RET	=	T0.U_ST2RET,
--			U_EN2RET	=	T0.U_EN2RET,
			U_GN2MON	=	T0.U_GN2MON,
			U_EX2MON	=	T0.U_EX2MON,
			U_GN2YER	=	T0.U_GN2YER,
			U_JINDAT	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_JINDAT,120),''),
			U_JOTDAT	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_JOTDAT,120),''),
			U_JONMON	=	T0.U_GNMDAY,  --종전법정근무월수(U_GNMDAY이전필드로대체)
			U_JEXMON	=	T0.U_JEXMON,
			U_JMMMON	=	T0.U_JMMMON,
			U_JI2DAT	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_JI2DAT,120),''),
			U_JO2DAT	=	ISNULL(CONVERT(NVARCHAR(10), T0.U_JO2DAT,120),''),
			U_JO2MON	=	T0.U_JO2MON,
			U_JE2MON	=	T0.U_JE2MON,
			U_JM2MON	=	T0.U_JM2MON,
			U_JS1RET	=	T0.U_JS1RET,
			U_JS1GON	=	T0.U_JS1GON,
			U_JS1STD	=	T0.U_JS1STD,
			U_JS1YSD	=	T0.U_JS1YSD,
			U_JS1YST	=	T0.U_JS1YST,
			U_JS1SAN	=	T0.U_JS1SAN,
			U_JS1STX	=	T0.U_JS1STX,
			U_JS1TAX	=	T0.U_JS1TAX,
			U_JS1GAB	=	T0.U_JS1GAB,
			U_JS2RET	=	T0.U_JS2RET,
			U_JS2GON	=	T0.U_JS2GON,
			U_JS2STD	=	T0.U_JS2STD,
			U_JS2YSD	=	T0.U_JS2YSD,
			U_JS2YST	=	T0.U_JS2YST,
			U_JS2SAN	=	T0.U_JS2SAN,
			U_JS2STX	=	T0.U_JS2STX,
			U_JS2TAX	=	T0.U_JS2TAX,
			U_JS2GAB	=	T0.U_JS2GAB,
			U_JSNRET	=	T0.U_JSNRET,
			U_RETGON	=	T0.U_RETGON,
			U_TAXSTD	=	T0.U_TAXSTD,
			U_YTXSTD	=	T0.U_YTXSTD,
			U_YSANTX	=	T0.U_YSANTX,
			U_SANTAX	=	T0.U_SANTAX,
			U_SPCGON	=	ISNULL(T0.U_SPCGON,0),
			U_TAXGON	=	T0.U_TAXGON,
			U_GULGAB	=	T0.U_GULGAB,
			U_GULJUM	=	T0.U_GULJUM,
			U_JONGAB	=	T0.U_JONGAB,
			U_JONJUM	=	T0.U_JONJUM,
			U_CHAGAB	=	T0.U_CHAGAB,
			U_CHAJUM	=	T0.U_CHAJUM,
			U_TAXNAM	=	T2.U_TAXName,			
			ISNULL(CONVERT(CHAR(10), T0.U_STRRET,20),'') AS U_STRRET, 
			ISNULL(CONVERT(CHAR(10), T0.U_ENDRET,20),'') AS U_ENDRET,
			ISNULL(CONVERT(CHAR(10), T0.U_INPDAT,20),'') AS U_INPDAT,
			ISNULL(CONVERT(CHAR(10), T0.U_OUTDAT,20),'') AS U_OUTDAT,
            FILIMG		= ''		--T6.FILIMG

--			T0.U_SUDAMT, 
--			T0.U_BHMAMT, 
--			T0.U_GULGAB, 
--			T0.U_GULJUM,
--			T0.U_JONGAB, 
--			T0.U_JONJUM, 
--			T0.U_CHAGAB, 
--			T0.U_CHAJUM, 
--			T0.U_GNMDAY, 
--			T0.U_RETGON, 
--			T0.U_TAXSTD, 
--			T0.U_YTXSTD,
--			T0.U_YSANTX, 
--			T0.U_SANTAX, 
--			T0.U_JSUD01, 
--			T0.U_JBHM01,
--			ISNULL(T4.U_TAXName, '') AS U_TAXNAM,
--			,	-- 종전제외월수

	FROM	[@PH_PY115A] T0 	
			INNER JOIN [@PH_PY001A]	T1 ON T0.U_MSTCOD = T1.Code
			--LEFT  JOIN [@ZPY106H]	T4 ON T4.CODE = T2.U_CLTCOD
			INNER JOIN [@PH_PY005A] T2 ON T1.U_CLTCOD = T2.U_CLTCode
			--LEFT JOIN [MDC_PAYPIC] T6 ON T6.EmpID = T2.U_CLTCOD * -1
	WHERE 	T0.U_ENDRET >= @STRDAT
	AND		T0.U_ENDRET <= @ENDDAT
	AND		T0.U_JIGBIL BETWEEN @STRJIG AND @ENDJIG
	-- 2009년 이전에는 중도정산을 받은적 있는 사람이 명예퇴직수당이 존재하는 경우에만 사용하였으나
	-- 2010년 부터는 이 서식으로 통일 됨
	AND   ((T0.U_INPDAT <> T0.U_STRRET AND T0.U_SUDAMT <> 0)
	OR		T0.U_ENDRET >= '2010-01-01') 
	AND		ISNULL(T1.U_CLTCOD, '')  LIKE @Branch                        
	AND		T1.U_TeamCode LIKE @MSTDPT                        
	AND		T0.U_MSTCOD LIKE @MSTCOD
	AND		T0.U_JSNGBN LIKE CASE @JOBGBN WHEN '1' THEN '1' 
									 WHEN '2' THEN '2'
									 ELSE '%' END
	ORDER BY  T0.U_MSTNAM,  T0.U_MSTCOD
	
	
	-- <3.조회 >ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ    
	SELECT * FROM [#RPY401] ORDER BY U_MSTCOD--, U_ENDRET


--THE END /////////////////////////////////////////////////////////////////////////////////////////////////
SET NOCOUNT OFF

--go
--Exec RPY401_2 '2013-01-01', '2013-03-25', '%', '1', '', '%', '2013-03-25', '2013-03-25'
