IF OBJECT_ID('PS_SD030_10') IS NOT NULL
BEGIN
	DROP PROC PS_SD030_10
END
GO
--EXEC PS_SD030_10 '19'
CREATE PROC PS_SD030_10
(
	@SD030HNo INT
)
AS
BEGIN
	CREATE TABLE #TEMP
	(
		Groups		NVARCHAR(100),
		DocEntry	NVARCHAR(100),
		DocDate		NVARCHAR(100),
		CardCode	NVARCHAR(100),
		CardName	NVARCHAR(100),
		DCardCode	NVARCHAR(100),
		DCardName	NVARCHAR(100),
		Address		NVARCHAR(100),
		Phone		NVARCHAR(100),
		HComments	NVARCHAR(100),
		RowNumber	NVARCHAR(100),
		ItemName	NVARCHAR(100),
		ItemCode	NVARCHAR(100),
		BoxQty		NUMERIC(19,6),
		ItemGroup	NVARCHAR(100),
		ItemType	NVARCHAR(100),
		ItemSize	NVARCHAR(100),
		SizeDesc	NVARCHAR(100),
		Box			NUMERIC(19,6),
		Qty			NUMERIC(19,6),
		Weight		NUMERIC(19,6),
		Quality		NVARCHAR(100),
		LComments	NVARCHAR(100)
	)
	DECLARE @DocEntry NVARCHAR(100)
	DECLARE @LineId NVARCHAR(100)
	DECLARE @ItmMsort NVARCHAR(100)
	DECLARE @RANK INT
	DECLARE @BeforeItmMsort NVARCHAR(100)
	DECLARE @CurrentItmMsort NVARCHAR(100)
	DECLARE @ROW_NUMBER INT
	SET @ROW_NUMBER = 0
	SET @RANK = 0
	SET @BeforeItmMsort = ''
	SET @CurrentItmMsort = ''
	
	DECLARE CURSOR01 SCROLL CURSOR FOR
	SELECT
		CONVERT(NVARCHAR(100),PS_SD030H.DocEntry) AS DocEntry,
		CONVERT(NVARCHAR(100),PS_SD030L.LineId) AS LineId,
		CONVERT(NVARCHAR(100),OITM.U_ItmMsort) AS ItmMsort
	FROM
		[@PS_SD030H] PS_SD030H
		LEFT JOIN [@PS_SD030L] PS_SD030L ON PS_SD030H.DocEntry = PS_SD030L.DocEntry
		LEFT JOIN [OITM] OITM ON OITM.ItemCode = PS_SD030L.U_ItemCode
	WHERE
		PS_SD030H.DocEntry = '19'--@SD030HNo
		AND PS_SD030H.U_BPLId IN('1','4')
		AND PS_SD030L.U_ItmBsort = '101'
	
	OPEN CURSOR01
	FETCH NEXT FROM CURSOR01 INTO @DocEntry,@LineId,@ItmMsort
	WHILE(@@FETCH_STATUS=0)
	BEGIN
		SET @CurrentItmMsort = @ItmMsort
		IF @BeforeItmMsort <> @CurrentItmMsort
		BEGIN
			SET @RANK = @RANK + 1
		END
		SET @ROW_NUMBER = @ROW_NUMBER +1
		
		INSERT INTO [#TEMP]
		SELECT
			CONVERT(NVARCHAR(100),@RANK) AS Groups,
			CONVERT(NVARCHAR(100),PS_SD030H.DocEntry) AS DocEntry,
			CONVERT(NVARCHAR(100),PS_SD030H.U_DocDate,112) AS DocDate,
			CONVERT(NVARCHAR(100),PS_SD030H.U_CardCode) AS CardCode,
			CONVERT(NVARCHAR(100),PS_SD030H.U_CardName) AS CardName,
			CONVERT(NVARCHAR(100),CASE WHEN ISNULL(PS_SD030H.U_DCardCod,'') = '' THEN PS_SD030H.U_CardCode ELSE PS_SD030H.U_DCardCod END) AS DCardCode,
			CONVERT(NVARCHAR(100),CASE WHEN ISNULL(PS_SD030H.U_DCardNam,'') = '' THEN PS_SD030H.U_CardName ELSE PS_SD030H.U_DCardNam END) AS DCardName,
			CONVERT(NVARCHAR(100),(SELECT Address FROM [OCRD] WHERE CardCode = CASE WHEN ISNULL(PS_SD030H.U_DCardCod,'') = '' THEN PS_SD030H.U_CardCode ELSE PS_SD030H.U_DCardCod END)) AS Address,
			CONVERT(NVARCHAR(100),(SELECT Phone1 FROM [OCRD] WHERE CardCode = CASE WHEN ISNULL(PS_SD030H.U_DCardCod,'') = '' THEN PS_SD030H.U_CardCode ELSE PS_SD030H.U_DCardCod END)) AS Phone,
			CONVERT(NVARCHAR(100),PS_SD030H.U_Comments) AS HComments,
			CONVERT(NVARCHAR(100),@ROW_NUMBER) AS RowNumber,		
			CONVERT(NVARCHAR(100),PS_SD030L.U_ItemName) AS ItemName,
			CONVERT(NVARCHAR(100),PS_SD030L.U_ItemCode) AS ItemCode,
			CONVERT(NUMERIC(19,6),OITM.U_UnitQ1) AS BoxQty,
			CONVERT(NVARCHAR(100),(SELECT ItmsGrpNam FROM [OITB] WHERE ItmsGrpCod = OITM.ItmsGrpCod)) AS ItemGroup,
			CONVERT(NVARCHAR(100),CASE WHEN OITM.U_ItemType IN('04','05','11') THEN '[' + (SELECT NAME FROM [@PSH_SHAPE] WHERE CODE = OITM.U_ItemType) + ']' ELSE (SELECT NAME FROM [@PSH_SHAPE] WHERE CODE = OITM.U_ItemType) END) AS ItemType,
			CONVERT(NVARCHAR(100),CASE WHEN OITM.U_Spec1 >= 250.0 THEN '(' + OITM.U_Size + ')' ELSE OITM.U_Size END) AS ItemSize,
			CONVERT(NVARCHAR(100),CASE WHEN OITM.U_ItmBsort = '10101' THEN CONVERT(NVARCHAR,OITM.U_TikAngle) + 'E' WHEN OITM.U_ItmBsort = '10102' THEN 'T' WHEN OITM.U_ItmBsort = '10103' THEN '(R)' WHEN OITM.U_ItmBsort = '10104' THEN 'S' WHEN OITM.U_ItmBsort = '10105' THEN 'C' WHEN OITM.U_ItmBsort = '10107' THEN (CASE WHEN OITM.U_Material = '10K' THEN '10F' WHEN OITM.U_Material = '20K' THEN '20F' ELSE '' END) ELSE '' END) AS SizeDesc,
			CONVERT(NUMERIC(19,6),PS_SD030L.U_Qty) AS Box, --박스
			CONVERT(NUMERIC(19,6),PS_SD030L.U_Weight) AS Qty, --수량
			CONVERT(NUMERIC(19,6),(OITM.U_UnWeight * PS_SD030L.U_Weight) / 1000) AS Weight, --이론중량
			CONVERT(NVARCHAR(100),OITM.U_Quality) AS Quality,
			CONVERT(NVARCHAR(100),PS_SD030L.U_Comments) AS LComments
		FROM
			[@PS_SD030H] PS_SD030H
			LEFT JOIN [@PS_SD030L] PS_SD030L ON PS_SD030H.DocEntry = PS_SD030L.DocEntry
			LEFT JOIN [OITM] OITM ON OITM.ItemCode = PS_SD030L.U_ItemCode
		WHERE
			PS_SD030H.DocEntry = @DocEntry
			AND PS_SD030L.LineId = @LineId
		
		SET @BeforeItmMsort = @ItmMsort
		FETCH NEXT FROM CURSOR01 INTO @DocEntry,@LineId,@ItmMsort
	END
	CLOSE CURSOR01
	DEALLOCATE CURSOR01
	
	SELECT 
		Groups,
		DocEntry,
		DocDate,
		CardCode,
		CardName,
		DCardCode,
		DCardName,
		Address,
		Phone,
		HComments,
		RowNumber,
		ItemName,
		ItemCode,
		BoxQty,
		ItemGroup,
		ItemType,
		ItemSize,
		SizeDesc,
		Box,
		Qty,
		Weight,
		Quality,
		LComments,
		(SELECT SUM(Box) FROM [#TEMP]) AS BoxSum,
		(SELECT SUM(Qty) FROM [#TEMP]) AS QtySum,
		(SELECT SUM(Weight) FROM [#TEMP]) AS WeightSum		
	 FROM [#TEMP]
END