
IF OBJECT_ID('PS_MM090_01') IS NOT NULL
BEGIN
	DROP PROC PS_MM090_01
END
GO
CREATE PROC PS_MM090_01
(
	@Date NVARCHAR(8)
)
AS
BEGIN

	DECLARE @Index INT
	SELECT @Index = ISNULL(MAX(CONVERT(INT,RIGHT(U_OutNum,3))),0)+1 FROM [@PS_MM090H] WHERE U_InDate = @Date
	SELECT CASE WHEN @Index < 10 THEN '00' + CONVERT(VARCHAR,@Index)
				WHEN @Index < 100 THEN '0' + CONVERT(VARCHAR,@Index)
				ELSE CONVERT(VARCHAR,@Index) END
END
