IF OBJECT_ID('COMBO_VALIDVALUES') IS NOT NULL
BEGIN
	DROP TABLE COMBO_VALIDVALUES
END
GO
CREATE TABLE COMBO_VALIDVALUES
(
	IDX BIGINT PRIMARY KEY IDENTITY(1,1),
	FORMUID NVARCHAR(50),
	ITEMUID NVARCHAR(50),
	COLUMNUID NVARCHAR(50),
	VALUE NVARCHAR(100),
	DESCRIPTION NVARCHAR(100)
)
GO
IF OBJECT_ID('COMBO_VALIDVALUES_INSERT') IS NOT NULL
BEGIN
	DROP PROC COMBO_VALIDVALUES_INSERT
END
GO
CREATE PROC COMBO_VALIDVALUES_INSERT
(
	@FORMUID NVARCHAR(50),
	@ITEMUID NVARCHAR(50),
	@COLUMNUID NVARCHAR(50),
	@VALUE NVARCHAR(100),
	@DESCRIPTION NVARCHAR(100)
)
AS
BEGIN
	IF(SELECT 
			COUNT(*)
		FROM 
			COMBO_VALIDVALUES 
		WHERE 
			(@FORMUID = '' OR FORMUID = @FORMUID)
			AND (@ITEMUID = '' OR ITEMUID = @ITEMUID)
			AND (@COLUMNUID = '' OR COLUMNUID = @COLUMNUID)
			AND (@VALUE ='' OR VALUE = @VALUE)
			AND (@DESCRIPTION = '' OR DESCRIPTION = @DESCRIPTION)
	) = 0 
	BEGIN
		INSERT INTO COMBO_VALIDVALUES VALUES(@FORMUID,@ITEMUID,@COLUMNUID,@VALUE,@DESCRIPTION)
	END
END
GO