IF OBJECT_ID('PS_PP040_04') IS NOT NULL
BEGIN
	DROP PROC PS_PP040_04
END
GO
--EXEC PS_PP040_04 '6-2'
--해당프로시져는 실적포인트를 적용하기로 하여서 사용하지 않을예정임
CREATE PROC PS_PP040_04 --해당공정이 바렐앞공정인지 Y,N
(	
	@OrdMgNum NVARCHAR(100)
)
AS
BEGIN
	DECLARE @CpCode NVARCHAR(100)
	SET @CpCode =
	(SELECT
		TOP 1 
		PS_PP030M.U_CpCode
	FROM
		[@PS_PP030M] PS_PP030M
		LEFT JOIN
		(SELECT
			PS_PP030H.DocEntry AS DocEntry,
			PS_PP030M.U_Sequence AS Sequence
		FROM
			[@PS_PP030H] PS_PP030H
			LEFT JOIN [@PS_PP030M] PS_PP030M ON PS_PP030H.DocEntry = PS_PP030M.DocEntry
		WHERE
			CONVERT(NVARCHAR,PS_PP030H.DocEntry) + '-' + CONVERT(NVARCHAR,PS_PP030M.LineId) = @OrdMgNum
		) CURRENTROW ON CURRENTROW.DocEntry = PS_PP030M.DocEntry
	WHERE
		PS_PP030M.U_Sequence > CURRENTROW.Sequence
	ORDER BY
		U_Sequence ASC
	)
	SELECT CASE WHEN @CpCode = 'CP30112' THEN 'Y' ELSE 'N' END --바렐공정이면 뒷공정이 바렐공정임
END