IF OBJECT_ID('PS_PP040_05') IS NOT NULL
BEGIN
	DROP PROC PS_PP040_05
END
GO
--EXEC PS_PP040_05 '4-8'
CREATE PROC PS_PP040_05 --해당공정이 실적포인트인지 Y,N
(	
	@OrdMgNum NVARCHAR(100)
)
AS
BEGIN	
	DECLARE @ResultYN NVARCHAR(100)
	SET @ResultYN =
	(SELECT
		PS_PP030M.U_ResultYN AS ResultYN --작업지시의 실적포인트
	FROM
		[@PS_PP030H] PS_PP030H
		LEFT JOIN [@PS_PP030M] PS_PP030M ON PS_PP030H.DocEntry = PS_PP030M.DocEntry		
	WHERE
		CONVERT(NVARCHAR,PS_PP030H.DocEntry) + '-' + CONVERT(NVARCHAR,PS_PP030M.LineId) = @OrdMgNum
	)
	SELECT CASE WHEN ISNULL(@ResultYN,'N') = 'Y' THEN 'Y' ELSE 'N' END --해당공정이 실적포인트이면
END