IF OBJECT_ID('PS_PP040_03') IS NOT NULL
BEGIN
	DROP PROC PS_PP040_03
END
GO
--EXEC PS_PP040_03 '6-2'
CREATE PROC PS_PP040_03 --다음공정알아오기
(	
	@OrdMgNum NVARCHAR(100)
)
AS
BEGIN
	SELECT
		TOP 1 
		CONVERT(NVARCHAR,PS_PP030M.DocEntry) + '-' + CONVERT(NVARCHAR,PS_PP030M.LineId)
	FROM
		[@PS_PP030M] PS_PP030M
		LEFT JOIN
		(SELECT
			PS_PP030H.DocEntry AS DocEntry,
			PS_PP030M.U_Sequence AS Sequence
		FROM
			[@PS_PP030H] PS_PP030H
			LEFT JOIN [@PS_PP030M] PS_PP030M ON PS_PP030H.DocEntry = PS_PP030M.DocEntry
		WHERE
			CONVERT(NVARCHAR,PS_PP030H.DocEntry) + '-' + CONVERT(NVARCHAR,PS_PP030M.LineId) = @OrdMgNum
		) CURRENTROW ON CURRENTROW.DocEntry = PS_PP030M.DocEntry
	WHERE
		PS_PP030M.U_Sequence > CURRENTROW.Sequence
	ORDER BY
		U_Sequence ASC
END